<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="FreeNowApi" duration-ms="3957" started-at="2021-01-06T15:49:51Z" finished-at="2021-01-06T15:49:55Z">
    <groups>
    </groups>
    <test name="FreeNowApiTests" duration-ms="3957" started-at="2021-01-06T15:49:51Z" finished-at="2021-01-06T15:49:55Z">
      <class name="apiTests.WorkflowTest">
        <test-method status="FAIL" signature="validateUserName()[pri:0, instance:apiTests.WorkflowTest@675d3402]" name="validateUserName" duration-ms="2295" started-at="2021-01-06T21:19:51Z" finished-at="2021-01-06T21:19:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [null] but found [Samantha]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [null] but found [Samantha]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at assertions.ValidationCaller.verifyUserName(ValidationCaller.java:28)
	at apiTests.WorkflowTest.validateUserName(WorkflowTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateUserName -->
        <test-method status="PASS" signature="validateUserPosts()[pri:0, instance:apiTests.WorkflowTest@675d3402]" name="validateUserPosts" duration-ms="1652" started-at="2021-01-06T21:19:53Z" finished-at="2021-01-06T21:19:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateUserPosts -->
      </class> <!-- apiTests.WorkflowTest -->
      <class name="config.RestAssuredConfig">
        <test-method status="PASS" signature="configure()[pri:0, instance:config.RestAssuredConfig@18be83e4]" name="configure" is-config="true" duration-ms="227" started-at="2021-01-06T21:19:51Z" finished-at="2021-01-06T21:19:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configure -->
      </class> <!-- config.RestAssuredConfig -->
    </test> <!-- FreeNowApiTests -->
  </suite> <!-- FreeNowApi -->
</testng-results>
